function Settings(link, keys))
{
    var path = link,
        order = keys;

    //this.

    /**
     * Reads a file with the settings
     * @param {Function} callback - function called after settings will be read
     */
    this.read = function(callback)
    {

    }

    /**
     * Writes settings to the file
     * @param {Function} callback - function called after settings will be read
     */
    this.write = function(callback)
    {

    }
}
